CheckerNetwork/spark-stats

fly.toml
See https://github.com/filecoin-station/spark-stats/pull/2#discussion_r1452752585
=> docs: remind us to sync Fly hard_limit and PG max

lib/handler.js, test/handler.test.js
Calling `new URL('//foo', 'http://127.0.0.1')` produces href `http://foo/`. As a result, we were treating all requests for paths starting with double slash as if no path was specified.
Links:
- https://github.com/filecoin-station/roadmap/issues/57
=> fix: handle request paths starting with //

lib/handler.js
Per the discussion in https://github.com/filecoin-station/spark-stats/pull/6#discussion_r1454930123
=> refactor: simplify handling of '//' in req.url

lib/stats-fetchers.js, test/handler.test.js
Before this change, daily RSR was sorted randomly, which caused our public dashboard to pick a wrong RSR value (we configured Grafana to use the Last item).
I was able to write a failing test only for one of the SQL queries (stats endpoints). The remaining changes are not covered by tests.
=> feat: sort items in responses by date

.gitignore, lib/handler.js, lib/platform-routes.js, lib/platform-stats-fetchers.js, lib/request-helpers.js, test/handler.test.js, test/platform-routes.test.js, test/test-helpers.js
Links:
filecoin-station/roadmap#96
=> Feat: Included API handling for fetching from daily_node_metrics

lib/platform-routes.js, lib/platform-stats-fetchers.js, lib/request-helpers.js, lib/stats-fetchers.js, test/platform-routes.test.js
Roadmap Issue: filecoin-station/roadmap#97
Follow up to https://github.com/filecoin-station/spark-stats/pull/71
=> Fix: Migrate to dedicated station count endpoints

observer/test/platform-stats.test.js
=> test: modify existing test for last_block_checked conflict update

README.md, stats/lib/request-helpers.js, stats/lib/stats-fetchers.js, stats/test/handler.test.js
`GET /retrieval-success-rate?from=2024-01-01&to=2024-01-31&nonZero=true`
@patrickwoodhead FYI, this is based on our discussion about the shortcomings of the current Public Spark Dashboard.
=> feat: fetch RSR for miners with non-zero RSR only

package-lock.json
It seems that Dependabot is no longer able to update this git-based dependency
after we introduced the monorepo layout in #118.
See e.g. this log: https://github.com/filecoin-station/spark-stats/network/updates/841403106
```
updater | 2024/06/13 07:24:55 INFO <job_841403106> Updating spark-evaluate from 534454c9b2323b67d50b159a3504de8a06eedcb2 to 9e175400652623f19569eecfd97706a77084ff36
updater | 2024/06/13 07:24:55 ERROR <job_841403106> Error processing spark-evaluate (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
updater | 2024/06/13 07:24:55 ERROR <job_841403106> No files were updated!
updater | 2024/06/13 07:24:55 ERROR <job_841403106> 
````
=> chore: bump spark-evaluate from 534454 to 2a9546

stats/lib/handler.js, stats/lib/platform-routes.js
In preparation for https://github.com/filecoin-station/spark-stats/pull/147#discussion_r1638158012, this makes the path handling more flexible (each route can use its own parsing logic, path segments can be parametrized) while keeping it short using the utility functions
=> stats: refactor path handling

db/index.js, db/typings.d.ts, stats/test/handler.test.js, stats/test/platform-routes.test.js
We never use a `PgPools` that isn't endable
=> Remove `EndablePgPools`

README.md, stats/lib/handler.js, stats/lib/stats-fetchers.js, stats/test/handler.test.js
Return a summary of deals for the selected interval. These values are a bit difficult to calculate on the Grafana side, but I find it easier to build them on our backend.
```js
{
total: '6900',
indexed: '709',
retrievable: '69'
}
```
Links:
- https://github.com/space-meridian/roadmap/issues/57
Screenshot from our internal dashboard to illustrate what I am trying to achieve:
=> feat: `GET /deals/summary`

observer/test/observer.test.js, stats/bin/spark-stats.js, stats/lib/platform-routes.js, stats/lib/platform-stats-fetchers.js, stats/test/platform-routes.test.js
Link: https://github.com/space-meridian/roadmap/issues/118
=> feat: add endpoint for participants with highest measurement count

README.md, observer/test/observer.test.js, stats/lib/platform-routes.js, stats/lib/platform-stats-fetchers.js, stats/lib/request-helpers.js, stats/test/platform-routes.test.js
Link: https://github.com/space-meridian/roadmap/issues/118
=> feat: add top earnings participant endpoint

stats/lib/platform-stats-fetchers.js, stats/lib/request-helpers.js, stats/test/platform-routes.test.js
Link: https://github.com/space-meridian/roadmap/issues/118
=> feat: request date keyword handling

stats/lib/platform-routes.js, stats/lib/platform-stats-fetchers.js, stats/test/platform-routes.test.js
For https://github.com/filecoin-station/site-backend/pull/14
Instead of making a breaking change, it's easier and more useful to expose `total_measurement_count` in addition to `accepted_measurement_count`.
=> Add `total_measurement_count` to `GET /measurements/daily`

.github/dependabot.yml, .github/workflows/ci.yml, README.md, db/index.js, db/package.json, db/typings.d.ts, package-lock.json, stats/bin/migrate.js, stats/lib/handler.js, stats/test/handler.test.js
Links:
- https://github.com/filecoin-station/spark-api/pull/388.
- https://github.com/filecoin-station/spark-api/pull/386
- https://github.com/filecoin-station/spark/issues/78
Out of the scope of this pull request:
- querying deals by allocator id
Example request:
```
GET /miner/f0814049/deals/eligible/summary
```
Example response:
```json
{
"minerId": "f0814049",
"dealCount": 10006,
"clients": [
{ "clientId": "f02516933", "dealCount": 6880 },
{ "clientId": "f02833886", "dealCount": 3126 }
]
}
```
Example request:
```
GET /clients/f0215074/deals/eligible/summary
```
Example response:
```json
{
"clientId": "f0215074",
"dealCount": 5350,
"providers": [
{ "minerId": "f0406478", "dealCount": 4592 },
{ "minerId": "f0814049", "dealCount": 758 }
]
}
```
=> feat: API for deals tracked per miner/client

README.md, db/package.json, package-lock.json, stats/lib/handler.js, stats/test/handler.test.js
- **deps: upgrade spark-api to latest**
- **feat: API for deals tracked per allocator**
Example request:
```
GET /allocator/f03015751/deals/eligible/summary
```
Example response:
```json
{
"allocatorId": "f03019831",
"dealCount": 117596,
"clients": [
{
"clientId": "f02056762",
"dealCount": 64674
},
{
"clientId": "f03146638",
"dealCount": 21405
}
]
}
```
Links:
- https://github.com/filecoin-station/spark/issues/78
- https://github.com/filecoin-station/spark-api/pull/393
=> feat: API for deals tracked per allocator

observer/test/observer.test.js, package-lock.json
@PatrickNercessian FYI, this pull request updates the dependency version to include https://github.com/filecoin-station/spark-evaluate/pull/311
How to upgrade your local checkout in case of problems:
```bash
rm -rf db/node_modules/spark-evaluate && npm ci
```
=> chore: upgrade spark-evaluate dependency

.github/workflows/ci.yml, db/index.js, db/package.json, db/typings.d.ts, observer/test/observer.test.js, package-lock.json, stats/bin/migrate.js, stats/bin/spark-stats.js, stats/lib/handler.js, stats/test/handler.test.js, stats/test/platform-routes.test.js
Rework the endpoints `{miner/client/allocator}/:id/deals/eligible/summary` to return a (temporary) redirect to spark-api, as discussed in https://github.com/filecoin-station/spark-stats/pull/194#discussion_r1713500083.
Links:
- https://github.com/filecoin-station/spark-api/pull/403
- https://github.com/filecoin-station/spark/issues/78
=> feat: handle eligible deal stats via spark-api

Dockerfile, observer/fly.toml, stats/fly.toml
Also rework Dockerfile to use `NPM_CONFIG_WORKSPACE` instead of `SERVICE`.
This is a follow-up for:
- https://github.com/filecoin-station/spark-api/pull/405
=> chore: fix Dockerfile linter errors

observer/test/observer.test.js, package-lock.json, stats/lib/stats-fetchers.js, stats/test/handler.test.js, stats/test/platform-routes.test.js
We made several breaking chanages in the spark-evaluate database schema & the code writing stats.
In this pull request, I am upgrading spark-evaluate to the latest version ([d2fe8ca7](https://github.com/filecoin-station/spark-evaluate/commit/d2fe8ca7170364e9b412efbd4c2fe997aa154551)) and fixing the test suite to pass.
This pull request DOES NOT fix the affected endpoints to return correct data,
that needs to be done in #210 and another pull request I'll create soon.
Most notable spark-evaluate changes we are bringing in:
- https://github.com/filecoin-station/spark-evaluate/pull/336
- https://github.com/filecoin-station/spark-evaluate/pull/341
- https://github.com/filecoin-station/spark-evaluate/pull/311
=> deps: upgrade spark-evaluate to d2fe8ca7

stats/lib/stats-fetchers.js, stats/test/handler.test.js
This is a follow-up for the PR linked below to fix the output of the endpoint
`GET /deals/daily`.
- https://github.com/filecoin-station/spark-evaluate/pull/336
- https://github.com/filecoin-station/spark-stats/pull/215
Roadmap task:
- https://github.com/space-meridian/roadmap/issues/156
=> fix: sum deal stats over miners and clients

observer/bin/spark-observer.js, observer/lib/telemetry.js, observer/package.json, package-lock.json
Monitor how long each loop takes to finish and what's the delay before the next
iteration, so that we can alert when things become too slow.
=> feat: telemetry - loop duration & delay

README.md, stats/lib/handler.js, stats/lib/stats-fetchers.js, stats/test/handler.test.js
- Adds per-miner RSR endpoint
- Closes issue #106
=> Add per-miner RSR

stats/lib/platform-stats-fetchers.js, stats/test/platform-routes.test.js
Closes #253
With this change, we don't need to manually copy transfers into the rewards releases spreadsheet any more.
=> Add individual daily transfers. Closes #253

README.md, stats/lib/platform-routes.js, stats/lib/platform-stats-fetchers.js, stats/test/platform-routes.test.js
For https://github.com/space-meridian/roadmap/issues/154#issuecomment-2511707545
https://chat.mistral.ai/chat/4c43d4a1-2126-4e17-b65c-8ba40afac14a
I modified to add `DISTINCT(day::TEXT)`, as we were otherwise getting redundant rows. I also changed `cumulative_participants` to an `INT` and renamed it to `participants`
=> Add accumulative daily participants

package-lock.json, stats/lib/handler.js, stats/lib/stats-fetchers.js, stats/test/handler.test.js
Adds routes for fetching global and per miner time to first byte stats.
Related to https://github.com/space-meridian/roadmap/issues/208
=> Add routes for time-to-first-byte stats

README.md, stats/lib/handler.js, stats/lib/stats-fetchers.js, stats/test/handler.test.js
Introduces an endpoint to retrieve miner timing summaries. This data will be utilized to display miner TTFB in a table on the Spark dashboard's main page.
Related to https://github.com/filecoin-station/spark-dashboard/pull/14#issuecomment-2595073358
=> Add endpoint for fetching miners timing summaries

.github/workflows/dependabot-auto-approve-always.yml, db/index.js, db/package.json, db/test-helpers.js, observer/package.json, package-lock.json, stats/package.json
Make spark-evaluate automatically upgradable by installing it via npm.
Closes #288
=> Make spark-evaluate automatically upgradable

observer/lib/observer.js
Rework `observeRetrievalResultCodes` to execute a single SQL query to update all daily codes in one go.
Before this change, we would run ~1k individual queries, consume a lot of CPU and trigger a CPU throttling alert.
As part of this change, I am also adding a console log to tell us how many rows - tuples (day, code) - we are updating in each loop iteration.
=> perf: optimise SQL query in observeRetrievalResultCodes

observer/lib/observer.js
- Fixes daily desktop observer query to use correct bucket, measurement and to filter station users by deployment type
Follow up of #311
=> Fix daily desktop observer query

db/migrations/007.do.drop-platform-column-from-daily-desktop-users.sql, db/test-helpers.js, observer/lib/observer.js, observer/test/observer.test.js, stats/lib/platform-routes.js, stats/lib/platform-stats-fetchers.js, stats/test/platform-routes.test.js
In my 1:1 with @patrickwoodhead, I raised the question of whether we need to track the platform used by desktop users to run the app. We concluded that we're only interested in the number of users running the Station app.
- Drop `platform` column from `daily_desktop_users` table
- Simplify InfluxDB query to only return daily desktop users count
- Add endpoint to read daily desktop users count in a given time range
Follow up #311 
Related to https://github.com/CheckerNetwork/roadmap/issues/207
=> Remove platform column and add endpoint to read daily desktop users

README.md, package-lock.json, stats/lib/routes.js, stats/lib/stats-fetchers.js, stats/lib/typings.d.ts, stats/package.json, stats/test/app.test.js
1. Per Client RSR summary endpoint
2. Clients RSR summary endpoint
The two new endpoints closely follow the implementation of the [per miner](https://github.com/CheckerNetwork/spark-stats/blob/main/stats/lib/routes.js#L67) and [miners](https://github.com/CheckerNetwork/spark-stats/blob/main/stats/lib/routes.js#L52) RSR summary endpoints. These existing endpoints expose `retrieval_stats` for miner-related statistics.  
This PR introduces the same logic for client-related statistics by exposing the `daily_client_retrieval_stats` table, which was created in this recent [PR](https://github.com/CheckerNetwork/spark-evaluate/pull/481/files).  
Additionally, the tests for these new endpoints follow the same pattern as those for the existing miner RSR stats endpoints, ensuring consistency and …
=> feat: per client rsr api endpoint

db/package.json, observer/package.json, package-lock.json, stats/lib/routes.js, stats/lib/stats-fetchers.js, stats/package.json, stats/test/app.test.js
This PR adds new endpoints to expose Retrieval Success Rate (RSR) statistics calculated on a per-allocator basis, as requested in #216.
- Added new endpoints to fetch retrieval success rate statistics for allocators:
- `/allocators/retrieval-success-rate/summary` - Gets summary stats across all allocators
- `/allocator/{id}/retrieval-success-rate/summary` - Gets daily stats for a specific allocator
- Added helper functions to fetch stats from the database:
- `fetchAllocatorsRSRSummary()` - Aggregates stats across allocators
- `fetchDailyAllocatorRSRSummary()` - Gets daily stats for single allocator
- Added comprehensive test coverage for new endpoints and helper functions
- Upgraded `@filecoin-station/spark-evaluate` from 1.2.0 to 1.3.0
```js
// Get summary for all allocators
GET …
```
=> feat: allocator rsr endpoints

README.md
Adds documentation in the README for the two endpoints that were recently added for per allocator rsr scores. 
Related to https://github.com/CheckerNetwork/spark-stats/pull/351
=> fix: update readme for per allocator RSR scores

observer/bin/dry-run.js, observer/bin/spark-observer.js, observer/lib/observer.js, observer/test/observer.test.js
Drop the code that's periodically updating the table `daily_scheduled_rewards` and the accompanying unit tests to make CI green.
Note: while I could drop the table `daily_scheduled_rewards` in this pull request, such a change would be more invasive, so I decided to leave that cleanup for another day.
=> feat! remove observeScheduledRewards
