.github/workflows/ci.yml
README.md
lib/handler.js
lib/stats-fetchers.js
lib/typings.d.ts
package-lock.json
package.json
test/handler.test.js

Implement the first API endpoint for retrieving Retrieval Success Rate.
As part of this work, I created helpers that will make subsequent enpoints
faster to build.
Links:
- https://github.com/filecoin-station/roadmap/issues/57
- https://github.com/filecoin-station/spark-stats/pull/2

feat: GET /retrieval-success-rate

---

lib/handler.js
test/handler.test.js

Links:
- https://github.com/filecoin-station/roadmap/issues/57

feat: health check at `GET /`

---

.github/workflows/dependabot-auto-approve-always.yml

Auto approves PRs like https://github.com/filecoin-station/spark-stats/pull/26

ci: add auto approve `spark-evaluate` updates

---

package-lock.json
test/handler.test.js

This fixes a regression introduced by https://github.com/filecoin-station/spark-evaluate/pull/177
Links:
- https://github.com/filecoin-station/roadmap/issues/65

test: add miner_id to dummy retrieval stats

---

lib/stats-fetchers.js
test/handler.test.js

Links:
- https://github.com/filecoin-station/spark-stats/pull/56
- https://github.com/filecoin-station/roadmap/issues/65

fix: sum daily retrievals from all miners

---

lib/handler.js
lib/stats-fetchers.js
test/handler.test.js

Visualisation:
Links:
- https://github.com/filecoin-station/roadmap/issues/65

feat: summary of RSR per miner

---

README.md
lib/handler.js
lib/stats-fetchers.js
test/handler.test.js

Implement a new API endpoint `GET /participants/change-rates`
Links:
- https://github.com/filecoin-station/roadmap/issues/91

feat: participant change rates (monthly)

---

README.md

Continue building a very minimal API docs.

docs: list all endpoints

---

lib/platform-routes.js
lib/platform-stats-fetchers.js
test/platform-routes.test.js

Link: https://github.com/filecoin-station/roadmap/issues/99

Feat: Add honest_measurement_count platform stat

---

.dockerignore
.github/workflows/ci.yml
Dockerfile
README.md
observer/bin/spark-observer.js
observer/fly.toml
observer/package.json
observer/test/smoke.test.js
package-lock.json
package.json

Add a new sub-project (package/workspace) for a new service `spark-observer`.
The initial version is very minimal; it listens for `Transfer` events and logs them to stdout.
Links:
- https://github.com/filecoin-station/roadmap/issues/109
/cc @PatrickNercessian

feat: add spark-observer service

---

observer/package.json
package-lock.json
stats/package.json

Links:
- https://github.com/filecoin-station/roadmap/issues/109

fix: typo in package names

---

Dockerfile

Links:
- https://github.com/filecoin-station/roadmap/issues/109

fix: add observer to Dockerfile

---

observer/lib/observer.js
observer/lib/platform-stats.js
observer/test/platform-stats.test.js
stats/test/platform-routes.test.js

Related to #102 comments after merging.

fix: pg test bug, naming convention, and error message reliance

---

stats/lib/platform-stats-fetchers.js
stats/lib/request-helpers.js
stats/lib/stats-fetchers.js
stats/lib/typings.d.ts

See https://github.com/filecoin-station/spark-stats/pull/131#discussion_r1632233070

refactor: rename Filter to DateRangeFilter

---

.github/workflows/ci.yml
db/index.js
db/typings.d.ts
observer/bin/spark-observer.js
observer/lib/observer.js
observer/lib/platform-stats.js
observer/test/observer.test.js
observer/test/platform-stats.test.js
package-lock.json
package.json
stats/bin/spark-stats.js
stats/lib/handler.js
stats/lib/platform-stats-fetchers.js
stats/lib/request-helpers.js
stats/lib/stats-fetchers.js
stats/test/handler.test.js
stats/test/platform-routes.test.js
stats/test/test-helpers.js
tsconfig.json

See https://github.com/space-meridian/roadmap/issues/80

chore: setup TypeScript and fix type errors

---

stats/test/handler.test.js

For https://github.com/filecoin-station/spark-stats/pull/142

Add scheduled rewards handler test

---

README.md
stats/lib/handler.js
stats/lib/platform-routes.js
stats/lib/request-helpers.js
stats/lib/stats-fetchers.js
stats/test/handler.test.js

As discussed in https://github.com/filecoin-station/spark-stats/pull/147#discussion_r1638158012

Update scheduled rewards url

---

README.md
stats/lib/handler.js
stats/lib/stats-fetchers.js
stats/test/handler.test.js

add get daily participant reward transfers

---

stats/lib/handler.js

Ref https://github.com/filecoin-station/spark-stats/pull/154#discussion_r1679087445

fix pass normalized pathname to handler

---

package.json

See the discussion in https://github.com/filecoin-station/spark-stats/pull/206

build: run TypeScript as part of `npm test`

---

observer/lib/observer.js
observer/test/observer.test.js

https://github.com/space-meridian/roadmap/issues/161

Add integrate `spark-rewards`

---

package-lock.json
stats/package.json

See:
- https://github.com/filecoin-station/spark-stats/pull/257
- https://github.com/filecoin-station/spark-stats/pull/258
- https://github.com/filecoin-station/spark-stats/pull/260

deps: upgrade @sentry/profiling-node to 8.40.0

---

stats/lib/instrument.js

stats: fix don't report 4xx errors to sentry. closes #299

---

.github/workflows/dependabot-auto-merge.yml

Copies dependabot-auto-merge.yml script from core-fly.
Closes #158

Fix: Copy dependabot-auto-merge.yml script

---

observer/lib/telemetry.js

- Fix InfluxDB bucket permission comment to reflect correct permissions for InfluxDB token

fix: InfluxDB bucket permission comment
